version: '2'

services:
  php:
    container_name: web
    build: ./php
    ports:
      - '80:80'
    restart: always
    volumes:
        - /home/lgoodinson/Projects/newwebsite/:/var/www/html/:z
    links:
      - "db"
  db:
    image: mysql
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./db:/docker-entrypoint-initdb.d:z
    ports:
      - "3306:3306" 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - db:db
    ports:
        - 8000:80
    environment:
        MYSQL_USER: avuser
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
